version: "3"
services:
 database:
  container_name: database
  command: --default-authentication-plugin=mysql_native_password
  image: mysql
  ports:
   - 3306:3306
  volumes:
   - ./database/OASIP_DB.sql:/docker-entrypoint-initdb.d/OASIP_DB.sql
  environment:
   - MYSQL_ROOT_PASSWORD=221
  restart: always
 backend:
  build: ./backend
  image: backend
  container_name: backend
  ports:
   - 8080:8080
  links:
   - database
  restart: always
 frontend:
  build: ./frontend
  container_name: frontend
  ports:
   - 80:80
  links:
   - backend
  restart: always
