-- MySQL Script generated by MySQL Workbench
-- Thu Apr 28 22:42:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OASIP_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OASIP_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OASIP_DB` DEFAULT CHARACTER SET utf8 ;
USE `OASIP_DB` ;

-- -----------------------------------------------------
-- Table `OASIP_DB`.`eventcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OASIP_DB`.`eventcategory` (
  `eventcategoryID` INT NOT NULL,
  `eventCategoryName` VARCHAR(100) NOT NULL,
  `eventCategoryDescription` VARCHAR(500) NULL,
  `eventDuration` INT NOT NULL,
  PRIMARY KEY (`eventcategoryID`))
ENGINE = InnoDB;

insert into eventcategory value(1, 'Project Management Clinic' , 'ตารางนัดหมายนี้ใช้สําหรับนัดหมาย project management clinic ในวิชา INT221 integrated project I ให้นักศึกษาเตรียมเอกสารที่เกี่ยวข้องเพื่อแสดงระหว่างขอคําปรึกษา' , 30) ;
insert into eventcategory value(2, 'DevOps-Infra Clinic' , 'Use this event category for DevOps/Infra clinic.' , 20) ;
insert into eventcategory value(3, 'Database Clinic' , 'ตารางนัดหมายนี้ใช้สําหรับนัดหมาย database clinic ในวิชา INT221 integrated project I' , 15) ;
insert into eventcategory value(4, 'Client-side Clinic' , 'ตารางนัดหมายนี้ใช้สำหรับนัดหมาย client-side clinic ในวิชา INT221 integrated project I' , 30) ;
insert into eventcategory (eventcategoryID, eventCategoryName , eventDuration)
value(5, 'Server-side Clinic' , 30) ;



-- -----------------------------------------------------
-- Table `OASIP_DB`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OASIP_DB`.`event` (
  `eventID` INT NOT NULL,
  `bookingName` VARCHAR(100) NOT NULL,
  `eventEmail` VARCHAR(50) NULL,
  `eventCategory` VARCHAR(100) NOT NULL,
  `eventStartTime` DATETIME NOT NULL,
  `eventDuration` INT NOT NULL,
  `eventNotes` VARCHAR(500) NULL,
  `eventcategoryID` INT NOT NULL,
  PRIMARY KEY (`eventID`, `eventcategoryID`),
  INDEX `fk_event_eventcategory_idx` (`eventcategoryID` ASC) VISIBLE,
  CONSTRAINT `fk_event_eventcategory`
    FOREIGN KEY (`eventcategoryID`)
    REFERENCES `OASIP_DB`.`eventcategory` (`eventcategoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

insert into event (eventID,bookingName,eventEmail,eventCategory,eventStartTime,eventDuration,eventcategoryID)
value(1, 'Somchai Jaidee(OR-7)' , 'somchai.jai@mail.kmutt.ac.th' , 'DevOps/Infra Clinic' , '2022-05-23 13:30:00' , 30 , 1) ;

insert into event value(2, 'Somsri Rakdee(SJ-3)' , 'somsri.rak@mail.kmutt.ac.th' , 'Project Management Clinic' , '2022-04-27 09:30:00' , 30 , 'ขอปรึกษาปัญหาเพื่อนไม่ช่วยงาน' , 1) ;

insert into event (eventID,bookingName,eventEmail,eventCategory,eventStartTime,eventDuration,eventcategoryID)
value(3, 'สมเกียรติ ขยันเรียน กลุ่ม TT-4' , 'somkiat.kay@kmutt.ac.th' , 'Database Clinic' , '2022-05-23 16:30:00' , 15 , 3) ;


commit;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
